"use client"

import {  Urbanist , Mulish } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "./context/AuthContext";
import { store } from "./redux/store"
import { Provider } from 'react-redux';



const mulish = Mulish({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-mulish",
});


const urbanist = Urbanist({
  variable: "--font-urbanist",
  subsets: ["latin"],
});



// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
        <AuthProvider>
        <Provider store={store}>
          <body
            className={`${urbanist.variable} ${mulish.variable} antialiased`}
          >
            {children}
          </body>
          </Provider>
        </AuthProvider>
      
    </html>
  );
}
